CRUD API for a todolist
BhujelVictor/django-rest-ToDo pull request #3
Opened 2024-01-04 11:07 UTC by BhujelVictor

# Pull Request

## Description
API that performs CRUD operation

## Changes Made
- Added CRUD API files for a todo app.

## Screenshots 
TaskListView

![TaskListView](https://github.com/BhujelVictor/django-rest-ToDo/assets/110024834/4e317117-7784-478b-b600-d5960422e0bd)

TaskAddView

![TaskAddView](https://github.com/BhujelVictor/django-rest-ToDo/assets/110024834/9cf6476f-9ab7-4200-a517-b124c8c34138)

TaskDeleteView

![TaskDeleteView](https://github.com/BhujelVictor/django-rest-ToDo/assets/110024834/5dbbaa72-f7aa-4c0b-aa6a-da06776b0e84)

TaskListViewAfter-Deletion-task3

![TaskListViewAfter-Deletion-task3](https://github.com/BhujelVictor/django-rest-ToDo/assets/110024834/f3518444-df9f-4126-9035-77dc524d499e)

TaskUpdateView

![TaskUpdateView](https://github.com/BhujelVictor/django-rest-ToDo/assets/110024834/718524e1-cfad-4e40-a218-f5333e4623ba)

TaskListViewAfterUpdate-on-task3

![TaskListViewAfterUpdate-on-task3](https://github.com/BhujelVictor/django-rest-ToDo/assets/110024834/219c4335-f839-4abd-bb52-17d7e4325975)

2024-01-04 11:46 UTC, Biplav-00 requested changes

2024-01-04 11:46 UTC, Biplav-00 commented on ToDo/serializers.py
> +        fields = ['id', 'title', 'due_date', 'created_date', 'completed']
rename it to is_complete

2024-01-04 11:46 UTC, Biplav-00 commented on ToDo/urls.py
> +    path('', HomeAPIView.as_view(), name='home'),
there are generally two view class
Task list view and task detail view

task list view consists of  (list task and post task)
task detail view consists of (get individual task by id , update and delete)

2024-01-04 11:46 UTC, Biplav-00 commented on ToDo/views.py
> +from ToDo.models import ToDoList
rename it to Todo

2024-01-04 11:46 UTC, Biplav-00 commented on ToDo/views.py
> +class TaskListView(APIView):
do changes by above comment

2024-01-04 11:46 UTC, Biplav-00 commented on accounts/urls.py
> +    path('api/register/', UserRegistrationView.as_view(), name='register-user'),
change register to register_user

2024-01-04 11:46 UTC, Biplav-00 commented on accounts/urls.py
> +    path('api/verify-email/', VerifyEmailView.as_view(), name='verify-email'),
change verify-email to verify-email

2024-01-04 11:46 UTC, Biplav-00 commented on accounts/urls.py
> +    path('api/resend-code/', ResendVerificationCodeView.as_view(), name='resend-code')
same here

2024-01-04 11:46 UTC, Biplav-00 commented on accounts/views.py
> +def generate_otp():
can we add this generate_otp() to service class and call it in the view

2024-01-04 11:46 UTC, Biplav-00 commented on accounts/views.py
> +        serializer = UserRegistrationSerializer(data=request.data)
i think it is better approach to shift the db related stuff to service class

2024-01-04 11:46 UTC, Biplav-00 commented on restToDo/asgi.py
> +"""
rename restTodo to rest_todo

2024-01-04 11:46 UTC, Biplav-00 commented on restToDo/urls.py
> +URL configuration for restToDo project.
can we remove unnecessary comments from all the code

only include the comments that are necessary

2024-01-04 11:46 UTC, Biplav-00 commented on restToDo/urls.py
> +Examples:
same here

2024-01-04 11:46 UTC, Biplav-00 commented on restToDo/wsgi.py
> +It exposes the WSGI callable as a module-level variable named ``application``.
same in all the files

2024-01-04 11:46 UTC, Biplav-00 commented on ToDo/apps.py
> +    name = 'ToDo'
rename it to todo

2024-01-04 11:46 UTC, Biplav-00 commented on ToDo/models.py
> +    created_date = models.DateTimeField(auto_now_add=True)
rename it to created_at

2024-01-04 11:46 UTC, Biplav-00 commented on ToDo/models.py
> +    due_date = models.DateTimeField(default=one_week_hence)
rename it to deadline or something meaningful name

2024-01-08 16:12 UTC, yonjans requested changes

2024-01-08 16:12 UTC, yonjans commented on accounts/views.py
> +class UserRegistrationView(APIView):
Add 2 line breaks.

2024-01-08 16:12 UTC, yonjans commented on accounts/serializers.py
> +                otp_record = OTP.objects.get(user=user, otp=otp, otp_created_at__gte=timezone.now() - timedelta(minutes=5))
What is the logic here? I think it should be fixed.

2024-01-08 16:12 UTC, yonjans commented on accounts/serializers.py
> +            otp_record.delete()
Do we need to remove record?

2024-01-09 07:02 UTC, merged